SET DEFINE OFF;
-- =============================================================================
-- JD Edwards EnterpriseOne 9.2 (JDEORCL / PRODDTA)
-- Hybrid MCP Analytical Views, Julian Date Converters & Autonomous Audit Log
-- =============================================================================

ALTER SESSION SET CONTAINER = JDEORCL;

-- Fix F0006 200-301 row if missing
MERGE INTO PRODDTA.F0006 d
USING (SELECT '     200-301' AS mcmcu FROM DUAL) s
ON (d.MCMCU = s.mcmcu)
WHEN NOT MATCHED THEN
  INSERT (MCMCU, MCSTYL, MCDL01, MCCO, MCAN8, MCRP01)
  VALUES ('     200-301', 'WC', 'Final Servo Assy & Calibration', '00200', 3013, 'M30');
COMMIT;

-- 1. Create JDE Julian Date (CYYDDD) <-> Oracle DATE Helper Functions
CREATE OR REPLACE FUNCTION PRODDTA.JDE_TO_DATE(p_julian IN NUMBER)
RETURN DATE DETERMINISTIC IS
  v_year NUMBER;
  v_ddd  NUMBER;
BEGIN
  IF p_julian IS NULL OR p_julian <= 0 THEN
    RETURN NULL;
  END IF;
  v_year := 1900 + TRUNC(p_julian / 1000);
  v_ddd  := MOD(p_julian, 1000);
  RETURN TO_DATE(TO_CHAR(v_year, 'FM0000') || '-' || TO_CHAR(v_ddd, 'FM000'), 'YYYY-DDD');
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION PRODDTA.DATE_TO_JDE(p_date IN DATE)
RETURN NUMBER DETERMINISTIC IS
BEGIN
  IF p_date IS NULL THEN
    RETURN 0;
  END IF;
  RETURN (TO_NUMBER(TO_CHAR(p_date, 'YYYY')) - 1900) * 1000
       + TO_NUMBER(TO_CHAR(p_date, 'DDD'));
END;
/

-- 2. Create Autonomous Audit Log Table (GGLTOOLBOX$MCP_LOG)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE PRODDTA.GGLTOOLBOX$MCP_LOG (
      LOG_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      LOG_TIMESTAMP  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      TOOL_NAME      VARCHAR2(128) NOT NULL,
      JDE_USER       VARCHAR2(64),
      WORK_ORDER_NUM NUMBER,
      PARAMETERS     CLOB,
      EXECUTION_MODE VARCHAR2(32) DEFAULT ''HYBRID_ORCH_SQL'',
      STATUS         VARCHAR2(32)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. View 1: Discrete Manufacturing Work Order Control Tower (F4801 + F4101 + F3111)
CREATE OR REPLACE VIEW PRODDTA.VW_JDE_MFG_WORK_ORDERS AS
WITH inv_summary AS (
  SELECT
      LIITM AS short_item,
      TRIM(LIMCU) AS branch_plant,
      SUM(NVL(LIPQOH, 0) - NVL(LIHCOM, 0) - NVL(LIPCOM, 0)) AS qty_available_net
  FROM PRODDTA.F41021
  GROUP BY LIITM, TRIM(LIMCU)
),
shortage_details AS (
  SELECT
      p.WMDOCO,
      COUNT(*) AS shortage_count
  FROM PRODDTA.F3111 p
  LEFT JOIN inv_summary inv
    ON inv.short_item = p.WMITM AND inv.branch_plant = TRIM(p.WMCMCU)
  WHERE (NVL(p.WMUORG, 0) - NVL(p.WMTRQT, 0)) > 0
    AND (NVL(p.WMUORG, 0) - NVL(p.WMTRQT, 0)) > NVL(inv.qty_available_net, 0)
  GROUP BY p.WMDOCO
)
SELECT
    w.WADOCO AS work_order_number,
    TRIM(w.WADCTO) AS order_type,
    TRIM(w.WAMCU) AS branch_plant,
    w.WAITM AS parent_short_item,
    TRIM(w.WALITM) AS parent_item_number,
    TRIM(w.WADSC1) AS item_description,
    TRIM(w.WASRST) AS status_code,
    CASE TRIM(w.WASRST)
      WHEN '10' THEN '10 - Entered'
      WHEN '20' THEN '20 - Reviewed'
      WHEN '30' THEN '30 - Released / Parts & Routing Attached'
      WHEN '40' THEN '40 - Released to Shop Floor'
      WHEN '45' THEN '45 - Material Issued / In Process at Work Center'
      WHEN '50' THEN '50 - In Production Operation'
      WHEN '80' THEN '80 - Pending Quality Inspection'
      WHEN '90' THEN '90 - Manufacturing Completed (IC)'
      WHEN '95' THEN '95 - Closed / Accounting Complete'
      WHEN '99' THEN '99 - Closed / Variances Posted'
      ELSE TRIM(w.WASRST) || ' - Active Manufacturing Status'
    END AS status_meaning,
    ROUND(NVL(w.WAUORG, 0) / 10000, 2) AS quantity_ordered,
    ROUND(NVL(w.WASOQS, 0) / 10000, 2) AS quantity_completed,
    ROUND(NVL(w.WASOCN, 0) / 10000, 2) AS quantity_scrapped,
    GREATEST(0, ROUND((NVL(w.WAUORG, 0) - NVL(w.WASOQS, 0)) / 10000, 2)) AS quantity_remaining,
    CASE
      WHEN NVL(w.WAUORG, 0) > 0 THEN ROUND((NVL(w.WASOQS, 0) / w.WAUORG) * 100, 1)
      ELSE 0
    END AS pct_complete,
    TO_CHAR(PRODDTA.JDE_TO_DATE(w.WASTRT), 'YYYY-MM-DD') AS start_date_iso,
    TO_CHAR(PRODDTA.JDE_TO_DATE(w.WADRQJ), 'YYYY-MM-DD') AS requested_date_iso,
    NVL(sd.shortage_count, 0) AS shortage_component_count,
    CASE
      WHEN TRIM(w.WASRST) >= '90' THEN 'COMPLETED'
      WHEN PRODDTA.JDE_TO_DATE(w.WADRQJ) < TRUNC(SYSDATE) THEN 'LATE'
      WHEN NVL(sd.shortage_count, 0) > 0 THEN 'AT_RISK_SHORTAGE'
      ELSE 'ON_TRACK'
    END AS schedule_health
FROM PRODDTA.F4801 w
LEFT JOIN shortage_details sd ON sd.WMDOCO = w.WADOCO
WHERE TRIM(w.WADCTO) = 'WO';

-- 4. View 2: Work Order Material Shortages & Open PO Supply (F3111 + F41021 + F4311)
CREATE OR REPLACE VIEW PRODDTA.VW_JDE_MFG_PARTS_SHORTAGES AS
WITH inv_summary AS (
  SELECT
      LIITM AS short_item,
      TRIM(LIMCU) AS branch_plant,
      ROUND(SUM(NVL(LIPQOH, 0)) / 10000, 2) AS qty_on_hand,
      ROUND(SUM(NVL(LIHCOM, 0) + NVL(LIPCOM, 0)) / 10000, 2) AS qty_committed,
      ROUND(SUM(NVL(LIPQOH, 0) - NVL(LIHCOM, 0) - NVL(LIPCOM, 0)) / 10000, 2) AS qty_available_net
  FROM PRODDTA.F41021
  GROUP BY LIITM, TRIM(LIMCU)
),
po_next AS (
  SELECT
      PDITM AS short_item,
      TRIM(PDMCU) AS branch_plant,
      MIN(PDDOCO) KEEP (DENSE_RANK FIRST ORDER BY PDPDDJ ASC) AS next_open_po_number,
      MIN(PDPDDJ) AS next_po_promised_julian
  FROM PRODDTA.F4311
  WHERE TRIM(PDDCTO) = 'OP'
    AND TRIM(PDLTTR) < '620'
    AND NVL(PDUORG, 0) > NVL(PDUREC, 0)
  GROUP BY PDITM, TRIM(PDMCU)
)
SELECT
    p.WMDOCO AS work_order_number,
    TRIM(w.WALITM) AS parent_item_number,
    ROUND(NVL(p.WMOPSQ, 1000) / 100, 1) AS operation_seq,
    TRIM(p.WMLITM) AS component_item_number,
    TRIM(p.WMDSC1) AS component_description,
    TRIM(p.WMCMCU) AS branch_plant,
    TRIM(p.WMUM) AS uom,
    ROUND(NVL(p.WMUORG, 0) / 10000, 2) AS qty_required,
    ROUND(NVL(p.WMTRQT, 0) / 10000, 2) AS qty_issued,
    GREATEST(0, ROUND((NVL(p.WMUORG, 0) - NVL(p.WMTRQT, 0)) / 10000, 2)) AS qty_open_required,
    NVL(inv.qty_on_hand, 0) AS qty_on_hand,
    NVL(inv.qty_committed, 0) AS qty_committed,
    NVL(inv.qty_available_net, 0) AS qty_available_net,
    GREATEST(0, ROUND((NVL(p.WMUORG, 0) - NVL(p.WMTRQT, 0)) / 10000, 2) - GREATEST(0, NVL(inv.qty_available_net, 0))) AS qty_shortage,
    CASE
      WHEN GREATEST(0, ROUND((NVL(p.WMUORG, 0) - NVL(p.WMTRQT, 0)) / 10000, 2) - GREATEST(0, NVL(inv.qty_available_net, 0))) > 0
      THEN 'SHORTAGE'
      ELSE 'AVAILABLE'
    END AS shortage_status,
    po.next_open_po_number,
    TO_CHAR(PRODDTA.JDE_TO_DATE(po.next_po_promised_julian), 'YYYY-MM-DD') AS next_po_promised_date_iso
FROM PRODDTA.F3111 p
JOIN PRODDTA.F4801 w
  ON w.WADOCO = p.WMDOCO
LEFT JOIN inv_summary inv
  ON inv.short_item = p.WMITM
 AND inv.branch_plant = TRIM(p.WMCMCU)
LEFT JOIN po_next po
  ON po.short_item = p.WMITM
 AND po.branch_plant = TRIM(p.WMCMCU);

-- 5. View 3: Work Center Capacity & Routing Bottlenecks (F3112 + F4801)
CREATE OR REPLACE VIEW PRODDTA.VW_JDE_MFG_ROUTING_LOAD AS
SELECT
    TRIM(r.WLMCU) AS work_center,
    MAX(TRIM(r.WLDSC1)) AS work_center_description,
    TRIM(w.WAMCU) AS branch_plant,
    COUNT(DISTINCT r.WLDOCO || '-' || r.WLOPSQ) AS open_operations_count,
    ROUND(SUM(NVL(r.WLSETL, 0)) / 100, 2) AS scheduled_setup_hours,
    ROUND(SUM(NVL(r.WLRUNM, 0)) / 100, 2) AS scheduled_machine_hours,
    ROUND(SUM(NVL(r.WLRUNL, 0)) / 100, 2) AS scheduled_labor_hours,
    ROUND(SUM(NVL(r.WLHRSA, 0) + NVL(r.WLHRSO, 0)) / 100, 2) AS completed_hours,
    GREATEST(0, ROUND(SUM(NVL(r.WLSETL, 0) + NVL(r.WLRUNM, 0) + NVL(r.WLRUNL, 0) - NVL(r.WLHRSA, 0) - NVL(r.WLHRSO, 0)) / 100, 2)) AS remaining_load_hours,
    80.0 AS weekly_capacity_hours,
    ROUND((GREATEST(0, SUM(NVL(r.WLSETL, 0) + NVL(r.WLRUNM, 0) + NVL(r.WLRUNL, 0) - NVL(r.WLHRSA, 0) - NVL(r.WLHRSO, 0)) / 100) / 80.0) * 100, 1) AS utilization_pct,
    CASE
      WHEN (GREATEST(0, SUM(NVL(r.WLSETL, 0) + NVL(r.WLRUNM, 0) + NVL(r.WLRUNL, 0) - NVL(r.WLHRSA, 0) - NVL(r.WLHRSO, 0)) / 100) / 80.0) * 100 >= 95
      THEN 'CRITICAL_BOTTLENECK'
      WHEN (GREATEST(0, SUM(NVL(r.WLSETL, 0) + NVL(r.WLRUNM, 0) + NVL(r.WLRUNL, 0) - NVL(r.WLHRSA, 0) - NVL(r.WLHRSO, 0)) / 100) / 80.0) * 100 >= 75
      THEN 'HIGH_LOAD'
      ELSE 'NORMAL'
    END AS bottleneck_status
FROM PRODDTA.F3112 r
JOIN PRODDTA.F4801 w
  ON w.WADOCO = r.WLDOCO
WHERE TRIM(w.WASRST) < '90'
GROUP BY TRIM(r.WLMCU), TRIM(w.WAMCU);

-- 6. View 4: Production Costing & Variance Analysis (F3102 + F4801)
CREATE OR REPLACE VIEW PRODDTA.VW_JDE_MFG_COST_VARIANCES AS
SELECT
    c.IGDOCO AS work_order_number,
    TRIM(w.WALITM) AS parent_item_number,
    TRIM(w.WADSC1) AS item_description,
    TRIM(c.IGMCU) AS branch_plant,
    TRIM(c.IGCOST) AS cost_type,
    CASE TRIM(c.IGCOST)
      WHEN 'A1' THEN 'A1 - Direct Material'
      WHEN 'B1' THEN 'B1 - Direct Labor'
      WHEN 'B2' THEN 'B2 - Machine Setup Labor'
      WHEN 'B3' THEN 'B3 - Machine Run Cost'
      WHEN 'C1' THEN 'C1 - Variable Manufacturing Overhead'
      WHEN 'C2' THEN 'C2 - Fixed Manufacturing Overhead'
      ELSE TRIM(c.IGCOST) || ' - Manufacturing Cost Element'
    END AS cost_type_description,
    ROUND(NVL(c.IGSTDC, 0) / 100, 2) AS standard_cost_usd,
    ROUND(NVL(c.IGPLNC, 0) / 100, 2) AS planned_cost_usd,
    ROUND(NVL(c.IGACTC, 0) / 100, 2) AS actual_cost_usd,
    ROUND(NVL(c.IGCSMT, 0) / 100, 2) AS completed_output_cost_usd,
    ROUND(NVL(c.IGSCRP, 0) / 100, 2) AS scrap_cost_usd,
    ROUND((NVL(c.IGACTC, 0) - NVL(c.IGSTDC, 0)) / 100, 2) AS total_variance_usd,
    CASE
      WHEN NVL(c.IGSTDC, 0) != 0
      THEN ROUND(((NVL(c.IGACTC, 0) - NVL(c.IGSTDC, 0)) / c.IGSTDC) * 100, 2)
      ELSE 0
    END AS variance_pct,
    CASE
      WHEN ABS(NVL(c.IGACTC, 0) - NVL(c.IGSTDC, 0)) / 100 >= 1000 THEN 'HIGH_VARIANCE'
      WHEN ABS(NVL(c.IGACTC, 0) - NVL(c.IGSTDC, 0)) / 100 >= 250  THEN 'MODERATE_VARIANCE'
      ELSE 'WITHIN_TOLERANCE'
    END AS variance_severity
FROM PRODDTA.F3102 c
JOIN PRODDTA.F4801 w
  ON w.WADOCO = c.IGDOCO;

EXIT;
