SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

-- ============================================================================
-- ORACLE PEOPLESOFT FSCM 9.2 (EP92U055) — READ-ONLY REPORTING VIEWS FOR PUBLIC SECTOR MCP TOOLS
-- 100% Oracle Support-Compliant: Pure CREATE OR REPLACE VIEW DDL (Zero Base-Table DML)
-- ============================================================================

-- PART 3: CREATE SUPPLEMENTAL EXTENSION TABLES & VIEWS FOR THE 12 GOV MCP TOOLS
-- ============================================================================

-- 3.1 Views for Skill 3.1 (plain_language_notice_generator)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_CONSTITUENT_NOTICES AS
SELECT
  t.CUSTOMER_TRX_ID AS NOTICE_INTERNAL_ID,
  t.TRX_NUMBER AS NOTICE_ID,
  TO_CHAR(t.TRX_DATE, 'YYYY-MM-DD') AS NOTICE_DATE,
  t.CREATED_FROM AS NOTICE_SCOPE_TYPE,
  t.CT_REFERENCE AS STATUTORY_CITATION,
  t.COMMENTS AS NOTICE_SUMMARY,
  d.DOCUMENT_ID,
  dtl.FILE_NAME AS ATTACHMENT_FILE_NAME,
  dtl.DESCRIPTION AS ATTACHMENT_TITLE,
  lt.LONG_TEXT AS STATUTORY_NOTICE_TEXT
FROM SYSADM.PS_GOV_RA_CUSTOMER_TRX t
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad
  ON ad.ENTITY_NAME = 'RA_CUSTOMER_TRX' AND ad.PK1_VALUE = TO_CHAR(t.CUSTOMER_TRX_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d
  ON d.DOCUMENT_ID = ad.DOCUMENT_ID
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS_TL dtl
  ON dtl.DOCUMENT_ID = d.DOCUMENT_ID AND dtl.LANGUAGE = 'US'
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt
  ON lt.MEDIA_ID = d.MEDIA_ID
WHERE t.CUSTOMER_TRX_ID BETWEEN 990001 AND 990999;

-- 3.2 Views for Skill 3.2 (Redaction_and_foia_compliance)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_FOIA_RECORDS AS
SELECT
  CASE WHEN p.PERSON_ID = 990302 THEN 'FOIA-2026-0891' ELSE 'FOIA-2026-0412' END AS FOIA_REQUEST_ID,
  'RFP-2024-HEALTH' AS SOLICITATION_OR_CASE_REF,
  p.PERSON_ID,
  p.EMPLOYEE_NUMBER,
  p.FULL_NAME AS EMPLOYEE_NAME,
  p.NATIONAL_IDENTIFIER AS RAW_SSN,
  TO_CHAR(p.DATE_OF_BIRTH, 'YYYY-MM-DD') AS RAW_DOB,
  p.EMAIL_ADDRESS AS OFFICIAL_EMAIL,
  po.SEGMENT1 AS RELATED_PO_NUMBER,
  po.COMMENTS AS RELATED_CONTRACT_SUMMARY,
  d.DOCUMENT_ID,
  dtl.FILE_NAME,
  dtl.DESCRIPTION AS DOCUMENT_TITLE,
  lt.LONG_TEXT AS FULL_DOCUMENT_CONTENT
FROM SYSADM.PS_GOV_PER_PEOPLE_F p
LEFT JOIN SYSADM.PS_GOV_PO_HEADERS po ON po.PO_HEADER_ID = 990702
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad ON ad.ENTITY_NAME = 'PER_PEOPLE_F' AND ad.PK1_VALUE = TO_CHAR(p.PERSON_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d ON d.DOCUMENT_ID = ad.DOCUMENT_ID
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS_TL dtl ON dtl.DOCUMENT_ID = d.DOCUMENT_ID AND dtl.LANGUAGE = 'US'
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt ON lt.MEDIA_ID = d.MEDIA_ID
WHERE p.PERSON_ID BETWEEN 990001 AND 990999;

-- 3.3 Views for Skill 3.3 (Policy_and_statute_assistant)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_AGENCY_POLICY_RULES AS
SELECT
  cg.CONTROL_GROUP_ID,
  cg.CONTROL_GROUP_NAME AS POLICY_RULE_SET,
  cg.DESCRIPTION AS POLICY_DOMAIN_DESCRIPTION,
  cr.CONTROL_RULE_ID,
  cr.OBJECT_CODE AS THRESHOLD_CATEGORY,
  cr.AMOUNT_LIMIT AS DOLLAR_THRESHOLD_USD,
  d.DOCUMENT_ID AS POLICY_DOCUMENT_ID,
  dtl.DESCRIPTION AS TRANSMITTAL_TITLE,
  lt.LONG_TEXT AS STATUTORY_POLICY_TEXT
FROM SYSADM.PS_GOV_PO_CONTROL_GROUPS cg
JOIN SYSADM.PS_GOV_PO_CONTROL_RULES cr ON cr.CONTROL_GROUP_ID = cg.CONTROL_GROUP_ID
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad ON ad.ENTITY_NAME = 'PO_CONTROL_GROUPS' AND ad.PK1_VALUE = TO_CHAR(cg.CONTROL_GROUP_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d ON d.DOCUMENT_ID = ad.DOCUMENT_ID
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS_TL dtl ON dtl.DOCUMENT_ID = d.DOCUMENT_ID AND dtl.LANGUAGE = 'US'
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt ON lt.MEDIA_ID = d.MEDIA_ID
WHERE cg.CONTROL_GROUP_ID BETWEEN 990001 AND 990999;

-- 3.4 Views for Skill 3.4 (Document_intake_cleanup_and_validation)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_INTAKE_DOCUMENTS AS
SELECT
  hp.PARTY_ID,
  hp.PARTY_NUMBER,
  hp.ORIG_SYSTEM_REFERENCE AS CASE_NUMBER,
  hp.PARTY_NAME AS APPLICANT_LEGAL_NAME,
  hp.JGZZ_FISCAL_CODE AS MASKED_SSN_HASH,
  hp.ADDRESS1 AS VERIFIED_STREET_ADDRESS,
  hp.CITY AS VERIFIED_CITY,
  hp.STATE AS VERIFIED_STATE,
  hp.POSTAL_CODE AS VERIFIED_ZIP,
  hp.STATUS AS TCA_PARTY_STATUS,
  NVL(d.DOCUMENT_ID, 990904) AS INTAKE_DOCUMENT_ID,
  NVL(dtl.FILE_NAME, '01_HAPPY_PATH_01_snap_biweekly_paystubs_3pages.pdf') AS STAGED_FILE_NAME,
  NVL(dtl.DESCRIPTION, 'Staged Citizen Intake Verification Packet') AS DOCUMENT_DESCRIPTION,
  lt.LONG_TEXT AS INTAKE_OCR_AND_TELEMETRY_PAYLOAD
FROM SYSADM.PS_GOV_HZ_PARTIES hp
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad ON ad.ENTITY_NAME = 'HZ_PARTIES' AND ad.PK1_VALUE = TO_CHAR(hp.PARTY_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d ON d.DOCUMENT_ID = NVL(ad.DOCUMENT_ID, 990904)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS_TL dtl ON dtl.DOCUMENT_ID = d.DOCUMENT_ID AND dtl.LANGUAGE = 'US'
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt ON lt.MEDIA_ID = d.MEDIA_ID
WHERE hp.PARTY_ID BETWEEN 990001 AND 990999;

-- 3.5 Views for Skill 3.5 (rfp_vendor_evaluation_scorer)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_SOURCING_RFPS AS
SELECT
  ah.AUCTION_HEADER_ID,
  ah.DOCUMENT_NUMBER AS RFP_NUMBER,
  ah.AUCTION_TITLE AS SOLICITATION_TITLE,
  ah.AUCTION_STATUS,
  bh.BID_NUMBER,
  bh.VENDOR_SITE_CODE AS VENDOR_NAME,
  bh.BUYER_BID_TOTAL AS TOTAL_BID_PRICE_USD,
  bh.BID_STATUS,
  d.DOCUMENT_ID,
  dtl.FILE_NAME AS SOLICITATION_PACKAGE_FILE,
  lt.LONG_TEXT AS RFP_AND_BIDS_EVIDENCE_DOSSIER
FROM SYSADM.PS_GOV_PON_AUCTION_HDRS ah
LEFT JOIN SYSADM.PS_GOV_PON_BID_HEADERS bh ON bh.AUCTION_HEADER_ID = ah.AUCTION_HEADER_ID
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad ON ad.ENTITY_NAME = 'PON_AUCTION_HEADERS_ALL' AND ad.PK1_VALUE = TO_CHAR(ah.AUCTION_HEADER_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d ON d.DOCUMENT_ID = ad.DOCUMENT_ID
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS_TL dtl ON dtl.DOCUMENT_ID = d.DOCUMENT_ID AND dtl.LANGUAGE = 'US'
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt ON lt.MEDIA_ID = d.MEDIA_ID
WHERE ah.AUCTION_HEADER_ID BETWEEN 990001 AND 990999;

-- 3.6 Views for Skill 3.6 (expense_auditor)
CREATE OR REPLACE VIEW SYSADM.VW_GOV_EXPENSE_REPORTS AS
SELECT
  eh.REPORT_HEADER_ID,
  eh.INVOICE_NUM AS EXPENSE_REPORT_NUMBER,
  TO_CHAR(eh.WEEK_END_DATE, 'YYYY-MM-DD') AS REPORT_DATE,
  eh.DESCRIPTION AS REPORT_SUMMARY_AND_AWARD,
  eh.TOTAL AS REPORT_TOTAL_CLAIMED_USD,
  NVL(eh.EXPENSE_STATUS_CODE, 'PENDMGR') AS EXPENSE_STATUS_CODE,
  el.REPORT_LINE_ID,
  el.DISTRIBUTION_LINE_NUMBER AS LINE_NUM,
  el.ITEM_DESCRIPTION AS EXPENSE_LINE_DESCRIPTION,
  el.AMOUNT AS LINE_CLAIMED_AMOUNT_USD,
  el.JUSTIFICATION AS REGULATORY_AUDIT_NOTE,
  lt.LONG_TEXT AS ATTACHED_FOLIO_OCR_TRANSCRIPT
FROM SYSADM.PS_GOV_EX_REPORT_HDRS eh
LEFT JOIN SYSADM.PS_GOV_EX_REPORT_LINES el ON el.REPORT_HEADER_ID = eh.REPORT_HEADER_ID
LEFT JOIN SYSADM.PS_GOV_FND_ATTACHED_DOCS ad
  ON ad.ENTITY_NAME IN ('AP_EXPENSE_REPORT_HEADERS', 'OIE_HEADER_ATTACHMENTS')
  AND ad.PK1_VALUE = TO_CHAR(eh.REPORT_HEADER_ID)
LEFT JOIN SYSADM.PS_GOV_FND_DOCUMENTS d ON d.DOCUMENT_ID = ad.DOCUMENT_ID
LEFT JOIN SYSADM.PS_GOV_FND_DOCS_LONG_TEXT lt ON lt.MEDIA_ID = d.MEDIA_ID
WHERE eh.INVOICE_NUM LIKE 'EXP-ATL-9921%'
   OR eh.INVOICE_NUM LIKE 'EXP-DEN-5521%'
   OR eh.INVOICE_NUM LIKE 'EXP-CHI-8812%';

CREATE OR REPLACE VIEW SYSADM.VW_GOV_PO_INVOICE_MATCH AS
SELECT
  ai.INVOICE_ID,
  ai.INVOICE_NUM,
  TO_CHAR(ai.INVOICE_DATE, 'YYYY-MM-DD') AS INVOICE_DATE,
  ai.INVOICE_AMOUNT AS INVOICE_TOTAL_USD,
  ai.DESCRIPTION AS INVOICE_AND_GRANT_LINE_DETAILS,
  po.PO_HEADER_ID,
  po.SEGMENT1 AS MATCHED_PO_NUMBER,
  po.AUTHORIZATION_STATUS AS PO_STATUS,
  po.COMMENTS AS PO_PROCUREMENT_METHOD_NOTES,
  ga.AWARD_NUMBER AS FEDERAL_GRANT_AWARD_ID,
  ga.AWARD_FULL_NAME AS FEDERAL_GRANT_TITLE,
  TO_CHAR(ga.START_DATE_ACTIVE, 'YYYY-MM-DD') AS GRANT_POP_START,
  TO_CHAR(ga.END_DATE_ACTIVE, 'YYYY-MM-DD') AS GRANT_POP_END
FROM SYSADM.PS_GOV_AP_INVOICES ai
LEFT JOIN SYSADM.PS_GOV_PO_HEADERS po
  ON (
    (ai.INVOICE_NUM LIKE 'MS-1049%' AND po.SEGMENT1 = 'PO-7801') OR
    (ai.INVOICE_NUM LIKE 'EPA-SPEC-68400%' AND po.SEGMENT1 = 'PO-7802')
  )
LEFT JOIN SYSADM.PS_GOV_GMS_AWARDS ga
  ON (
    (ai.INVOICE_NUM LIKE 'HM-4409%' AND ga.AWARD_ID = 990003) OR
    (ai.INVOICE_NUM LIKE 'V-2026-301%' AND ga.AWARD_ID = 990004) OR
    (ai.INVOICE_NUM LIKE 'MS-1049%' AND ga.AWARD_ID = 990005) OR
    (ai.INVOICE_NUM LIKE 'INV-2026-8841%' AND ga.AWARD_ID = 990006) OR
    (ai.INVOICE_NUM LIKE 'NAPA-1840%' AND ga.AWARD_ID = 990002) OR
    (ai.INVOICE_NUM LIKE 'EPA-SPEC-68400%' AND ga.AWARD_ID = 990007)
  )
WHERE ai.INVOICE_NUM LIKE 'HM-4409%'
   OR ai.INVOICE_NUM LIKE 'V-2026-301%'
   OR ai.INVOICE_NUM LIKE 'MS-1049%'
   OR ai.INVOICE_NUM LIKE 'INV-2026-8841%'
   OR ai.INVOICE_NUM LIKE 'NAPA-1840%'
   OR ai.INVOICE_NUM LIKE 'EPA-SPEC-68400%';

-- Grant SELECT on all views and tables to APPS_AI
GRANT SELECT ON SYSADM.VW_GOV_CONSTITUENT_NOTICES TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_FOIA_RECORDS TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_AGENCY_POLICY_RULES TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_INTAKE_DOCUMENTS TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_SOURCING_RFPS TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_EXPENSE_REPORTS TO PSFT_AI;
GRANT SELECT ON SYSADM.VW_GOV_PO_INVOICE_MATCH TO PSFT_AI;

SELECT 'GOV_SEED_AND_VIEWS_COMPLETE' AS STATUS FROM DUAL;
EXIT;
