SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON

-- 1. Create log table in APPS
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM all_tables WHERE owner = 'APPS' AND table_name = 'GGLTOOLBOX$MCP_LOG';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE APPS.GGLTOOLBOX$MCP_LOG (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        MCP_CLIENT VARCHAR2(200 BYTE) DEFAULT ''mcp-toolbox-ebs'' NOT NULL ENABLE,
        LOG_LEVEL VARCHAR2(200 BYTE),
        PROGRAM_UNIT VARCHAR2(100 BYTE),
        USERNAME VARCHAR2(100 BYTE),
        LOG_MESSAGE CLOB DEFAULT NULL,
        CREATED_ON TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
        CREATED_BY VARCHAR2(100 BYTE) DEFAULT USER NOT NULL ENABLE
      )';
  END IF;
END;
/

-- 2. Create MCP_TOOLBOX_LOG helper procedure in APPS (called by ge_ebs_mcp_tools)
CREATE OR REPLACE PROCEDURE APPS.MCP_TOOLBOX_LOG (
    p_log_message  IN CLOB,
    p_log_level    IN VARCHAR2 DEFAULT 'INFO',
    p_username     IN VARCHAR2 DEFAULT NULL,
    p_program_unit IN VARCHAR2 DEFAULT NULL,
    p_mcp_client   IN VARCHAR2 DEFAULT 'mcp-toolbox-ebs'
) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO APPS.GGLTOOLBOX$MCP_LOG (
        MCP_CLIENT,
        LOG_LEVEL,
        PROGRAM_UNIT,
        USERNAME,
        LOG_MESSAGE
    ) VALUES (
        NVL(p_mcp_client, 'mcp-toolbox-ebs'),
        p_log_level,
        p_program_unit,
        p_username,
        p_log_message
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END MCP_TOOLBOX_LOG;
/
SHOW ERRORS PROCEDURE APPS.MCP_TOOLBOX_LOG;

-- 3. Compile GE_EBS_MCP_TOOLS package spec and body in APPS
@ge_ebs_mcp_tools.pls
SHOW ERRORS PACKAGE APPS.GE_EBS_MCP_TOOLS;

@ge_ebs_mcp_tools.plb
SHOW ERRORS PACKAGE BODY APPS.GE_EBS_MCP_TOOLS;

-- 4. Verify package status
COLUMN owner FORMAT A10
COLUMN object_name FORMAT A25
COLUMN object_type FORMAT A15
COLUMN status FORMAT A10
SELECT owner, object_name, object_type, status
  FROM all_objects
 WHERE object_name IN ('GE_EBS_MCP_TOOLS', 'MCP_TOOLBOX_LOG', 'GGLTOOLBOX$MCP_LOG')
 ORDER BY object_name, object_type;

EXIT;
